// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/domain-packs" | "/api/domain-packs/[id]" | "/api/fs/children" | "/api/llm/models" | "/api/presets" | "/api/presets/[id]" | "/api/projects" | "/api/projects/[id]" | "/api/projects/[id]/analyze" | "/api/projects/[id]/ask" | "/api/projects/[id]/debug" | "/api/projects/[id]/file" | "/api/projects/[id]/index" | "/api/projects/[id]/runs" | "/api/projects/[id]/search" | "/api/runs" | "/api/runs/[id]" | "/api/runs/[id]/artifacts" | "/api/runs/[id]/events"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/domain-packs": {}
  "/api/domain-packs/[id]": { "id": string; }
  "/api/fs/children": {}
  "/api/llm/models": {}
  "/api/presets": {}
  "/api/presets/[id]": { "id": string; }
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/[id]/analyze": { "id": string; }
  "/api/projects/[id]/ask": { "id": string; }
  "/api/projects/[id]/debug": { "id": string; }
  "/api/projects/[id]/file": { "id": string; }
  "/api/projects/[id]/index": { "id": string; }
  "/api/projects/[id]/runs": { "id": string; }
  "/api/projects/[id]/search": { "id": string; }
  "/api/runs": {}
  "/api/runs/[id]": { "id": string; }
  "/api/runs/[id]/artifacts": { "id": string; }
  "/api/runs/[id]/events": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
